server.port: 8091
spring.application.name: weather-proxy

app.config-server: localhost
app.database: localhost

spring:
  cloud:
    config:
      import-check:
        enabled: false
  cloud.config:
    failFast: true
    retry:
      initialInterval: 3000
      multiplier: 1.3
      maxInterval: 10000
      maxAttempts: 20
    uri: http://${app.config-server}:8888

---
spring.config.activate.on-profile: docker
spring.config.import: "configserver:"
app.config-server: config-server
app.database: postgres
---
spring.config.activate.on-profile: test
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
